Added change email address feature
starlabspro-internship/ReviveIt pull request #100
Opened 2024-12-24 18:00 UTC by RedonAdemi

Also username will change with email address like it was to aspnet users

2024-12-25 08:05 UTC, NathanAmanuelG approved these changes

2024-12-26 09:14 UTC, EdisonAlushaj requested changes

2024-12-26 09:14 UTC, EdisonAlushaj commented on ReviveIT/Application/DTO/ChangeEmailDto.cs
> +
delete the white line

2024-12-26 10:11 UTC, EdisonAlushaj approved these changes

2024-12-26 10:13 UTC, merged