feat/added-reviews-table
starlabspro-internship/ReviveIt pull request #16
Opened 2024-11-01 13:18 UTC by NathanAmanuelG

2024-11-03 21:30 UTC, donatgosalcii requested changes

2024-11-03 21:30 UTC, donatgosalcii commented on ReviveIT/Domain/Configurations/ReviewsConfiguration.cs
> +
Remove empty line

2024-11-03 21:30 UTC, donatgosalcii commented on ReviveIT/Domain/Configurations/ReviewsConfiguration.cs
> +            builder.HasKey(r => r.ReviewID);
Add a new line for each parameter

2024-11-03 21:30 UTC, donatgosalcii commented on ReviveIT/Domain/Entities/Reviews.cs
> +
Remove empty line

2024-11-03 21:30 UTC, donatgosalcii commented on ReviveIT/Infrastructure/Data/ApplicationDbContext.cs
> +
Remove empty line

2024-11-03 21:30 UTC, donatgosalcii commented on ReviveIT/Infrastructure/Data/ApplicationDbContext.cs
> +            builder.ApplyConfiguration(new ReviewsConfiguration()); // Nathan
Remove the name from comments (//Nathan)

2024-11-04 07:57 UTC, NathanAmanuelG commented on ReviveIT/Infrastructure/Data/ApplicationDbContext.cs
> +            builder.ApplyConfiguration(new ReviewsConfiguration()); // Nathan
done

2024-11-04 07:58 UTC, NathanAmanuelG commented on ReviveIT/Domain/Entities/Reviews.cs
> +
ok

2024-11-04 08:18 UTC, betimtasholli commented on ReviveIT/Domain/Entities/Reviews.cs
> +    // Nathan
Remove Comments like this

2024-11-04 08:20 UTC, NathanAmanuelG commented on ReviveIT/Domain/Entities/Reviews.cs
> +    // Nathan
donat already addressed this point

2024-11-04 08:20 UTC, donatgosalcii approved these changes
Requested changes complete.

2024-11-04 08:30 UTC, betimtasholli approved these changes

2024-11-04 08:47 UTC, merged