Readme.md file updated
starlabspro-internship/ReviveIt pull request #18
Opened 2024-11-05 19:16 UTC by RedonAdemi

2024-11-05 22:43 UTC, donatgosalcii requested changes
Check this PR, you should close this and commit the readme file to the other PR, because it will just overwrite the code of the PR that gets approved first.

2024-11-05 22:43 UTC, donatgosalcii commented on ReviveIT/Application/Common/Exceptions/UrlGuard.cs
> +        // List of unsafe patterns or keywords, including single characters
Remove comments on this class for a cleaner code.

2024-11-05 22:43 UTC, donatgosalcii commented on ReviveIT/WebUI/Middlewares/ExceptionMiddleware.cs
> +    // Middleware class for handling exceptions and unsafe URLs
Remove comments here too.

2024-11-06 07:15 UTC, RedonAdemi commented
> Check this PR, you should close this and commit the readme file to the other PR, because it will just overwrite the code of the PR gets approved first.

Its seperated from other pr

2024-11-06 09:53 UTC, closed without merging