Added UrlGuard.cs and updated ExceptionMiddleware.cs
starlabspro-internship/ReviveIt pull request #19
Opened 2024-11-05 19:22 UTC by RedonAdemi

Also put some comment about code

2024-11-05 22:39 UTC, donatgosalcii requested changes
Pastroje kodin prej unescessary comments edhe check for white lines or spaces

2024-11-05 22:39 UTC, donatgosalcii commented on ReviveIT/Application/Common/Exceptions/UrlGuard.cs
> +        // List of unsafe patterns or keywords, including single characters
Remove comments from the code (refactor it).

2024-11-05 22:39 UTC, donatgosalcii commented on ReviveIT/WebUI/Middlewares/ExceptionMiddleware.cs
> +    // Middleware class for handling exceptions and unsafe URLs
Remove comments from this class too.

2024-11-05 22:39 UTC, donatgosalcii commented on ReviveIT/WebUI/Middlewares/ExceptionMiddleware.cs
> +                _logger.LogError(
It was already made, but more readable like this, remove the comments.

2024-11-06 07:45 UTC, RedonAdemi commented on ReviveIT/WebUI/Middlewares/ExceptionMiddleware.cs
> +                _logger.LogError(
Donat recheck the code again - its changed now

2024-11-06 09:44 UTC, donatgosalcii approved these changes

2024-11-06 09:57 UTC, NathanAmanuelG approved these changes
The code is solid though I'd recommend you tone down refactoring your code so mush, less is more, either way good job!

2024-11-06 11:54 UTC, merged