Made some of the navbar elements dynamic, such as the fullname, pfp and the status of the account, in the dropdown menu.
starlabspro-internship/ReviveIt pull request #58
Opened 2024-12-01 14:22 UTC by donatgosalcii

2024-12-01 21:36 UTC, EdisonAlushaj requested changes

2024-12-01 21:36 UTC, EdisonAlushaj commented on ReviveIT/WebUI/Controllers/ProfileUpdate.cs
> +
Delete the white line in line-40

2024-12-01 21:55 UTC, EdisonAlushaj approved these changes

2024-12-02 07:22 UTC, NathanAmanuelG commented on ReviveIT/WebUI/wwwroot/css/style.css
you should isolate the CSS changes into there own file,

2024-12-02 08:01 UTC, donatgosalcii commented on ReviveIT/WebUI/wwwroot/css/style.css
I didn't think so, since the changes are for the navbar, which is present throughout our web-app, most of the time, therefore, the general styling one felt more appropriate.

2024-12-02 08:41 UTC, NathanAmanuelG approved these changes

2024-12-02 08:57 UTC, merged