Removed Manuel insertion, Job board now uses API working, …
starlabspro-internship/ReviveIt pull request #90
Opened 2024-12-20 13:18 UTC by NathanAmanuelG

…I could not get user identification to work,  this will be addressed next push

2024-12-20 14:07 UTC, donatgosalcii approved these changes

2024-12-20 14:47 UTC, EdisonAlushaj requested changes

2024-12-20 14:47 UTC, EdisonAlushaj commented on ReviveIT/WebUI/Views/JobBoard/JobBoard.cshtml
> +
Delete the white lines in 186 and 187

2024-12-23 08:13 UTC, betimtasholli approved these changes

2024-12-23 09:20 UTC, EdisonAlushaj approved these changes

2024-12-23 09:20 UTC, merged